Repository ocaml/ocaml.org, pull requests merged in 2024-03, with the labels that each got.

#2134 (data) Add OCaml Retreat Auroville
  data/events/2024-03-10-ocaml-retreat-auroville.md
  data/events/recurring.yml
Labels: stalled

#2127 Cookbook : fix in Lwt (type mismatch with iter_s/iter_p functions)
  data/cookbook/concurrency/lwt/00-lwt.ml
Labels: documentation, Cookbook

#2196 Turn exercise 011 into practice
  practice/011/answer/impl.ml
  practice/011/answer/test/dune
  practice/011/answer/test/run.ml
  practice/011/dune
  practice/011/dune-project
  practice/011/ex.ml
  practice/011/work/impl.ml
  practice/011/work/test/dune
  practice/011/work/test/run.ml
Labels: outreachy

#2193 Make exercise 004 practice
  practice/004/answer/impl.ml
  practice/004/answer/test/dune
  practice/004/answer/test/run.ml
  practice/004/dune
  practice/004/dune-project
  practice/004/ex.ml
  practice/004/work/impl.ml
  practice/004/work/test/dune
  practice/004/work/test/run.ml
Labels: outreachy

#2192 Turn exercise 005 into practice
  practice/005/answer/impl.ml
  practice/005/answer/test/dune
  practice/005/answer/test/run.ml
  practice/005/dune
  practice/005/dune-project
  practice/005/ex.ml
  practice/005/work/impl.ml
  practice/005/work/test/dune
  practice/005/work/test/run.ml
Labels: outreachy

#2126 Update 00-caqti-ppx-rapper.ml - fix caqti-driver-sqlite -> caqti-driver-sqlite3
  data/cookbook/database/caqti-ppx-rapper/00-caqti-ppx-rapper.ml
Labels: documentation, Cookbook

#2277 Turned exercise 060 into practice
  practice/060/answer/impl.ml
  practice/060/answer/test/dune
  practice/060/answer/test/run.ml
  practice/060/dune
  practice/060/dune-project
  practice/060/ex.ml
  practice/060/work/impl.ml
  practice/060/work/test/dune
  practice/060/work/test/run.ml
Labels: outreachy

#2276 Turned exercise 059 into practice
  practice/059/answer/impl.ml
  practice/059/answer/test/dune
  practice/059/answer/test/run.ml
  practice/059/dune
  practice/059/dune-project
  practice/059/ex.ml
  practice/059/work/impl.ml
  practice/059/work/test/dune
  practice/059/work/test/run.ml
Labels: outreachy

#2233 Turn exercise 026 to practice
  practice/026/answer/impl.ml
  practice/026/answer/test/dune
  practice/026/answer/test/run.ml
  practice/026/dune
  practice/026/dune-project
  practice/026/ex.ml
  practice/026/work/impl.ml
  practice/026/work/test/dune
  practice/026/work/test/run.ml
Labels: outreachy

#2231 Turn exercise 024 to practice
  practice/024/answer/impl.ml
  practice/024/answer/test/dune
  practice/024/answer/test/run.ml
  practice/024/dune
  practice/024/dune-project
  practice/024/ex.ml
  practice/024/work/impl.ml
  practice/024/work/test/dune
  practice/024/work/test/run.ml
Labels: outreachy

#2230 Turn exercise 023 to practice
  practice/023/answer/impl.ml
  practice/023/answer/test/dune
  practice/023/answer/test/run.ml
  practice/023/dune
  practice/023/dune-project
  practice/023/ex.ml
  practice/023/work/impl.ml
  practice/023/work/test/dune
  practice/023/work/test/run.ml
Labels: outreachy

#2284 Turn exercise 003 into practice
  practice/003/answer/impl.ml
  practice/003/answer/test/dune
  practice/003/answer/test/run.ml
  practice/003/dune
  practice/003/dune-project
  practice/003/ex.ml
  practice/003/work/impl.ml
  practice/003/work/test/dune
  practice/003/work/test/run.ml
Labels: outreachy

#2236 Turn exercise 031 to practice
  data/exercises/031_is_prime.md
  practice/031/answer/impl.ml
  practice/031/answer/test/dune
  practice/031/answer/test/run.ml
  practice/031/dune
  practice/031/dune-project
  practice/031/ex.ml
  practice/031/work/impl.ml
  practice/031/work/test/dune
  practice/031/work/test/run.ml
Labels: outreachy

#2241 Fixes: Add a badge from the green web foundation to the carbon footprint page
  data/media/pages/green-web-foundation-badge.png
  data/pages/carbon_footprint.md
Labels: outreachy
