Repository ocaml/ocaml.org, pull requests merged in 2024-01, with the labels that each got.

#1376 Include @gmevel proof-reading of Seq tutorial
  data/tutorials/language/3ds_05_seq.md
Labels: documentation

#1825 Create tutorial: Running Commands in an Opam Switch
  data/tutorials/platform/bp_09_opam_path.md
Labels: documentation, new-doc

#948 Import Rewrote Set Tutorial from V2 PR
  data/tutorials/language/3ds_03_set.md
Labels: documentation

#1619 Render the Author of a Blog Post and the Source
  src/ocamlorg_frontend/pages/blog.eml
Labels: outreachy

#1604 Task #1579 : Added Dune Dependancy Copy Button
  src/ocamlorg_frontend/pages/package_overview.eml
Labels: outreachy

#1799 Add Package Versions Page
  src/global/url.ml
  src/ocamlorg_frontend/components/icons.eml
  src/ocamlorg_frontend/components/package_breadcrumbs.eml
  src/ocamlorg_frontend/css/styles.css
  src/ocamlorg_frontend/dune
  src/ocamlorg_frontend/ocamlorg_frontend.ml
  src/ocamlorg_frontend/package.ml
  src/ocamlorg_frontend/pages/package_overview.eml
  src/ocamlorg_frontend/pages/package_versions.eml
  src/ocamlorg_package/lib/ocamlorg_package.ml
  src/ocamlorg_package/lib/ocamlorg_package.mli
  src/ocamlorg_web/lib/handler.ml
  src/ocamlorg_web/lib/router.ml
Labels: outreachy

#1960 Add link to the operator table
  data/tutorials/language/4ad_01_operators.md
Labels: documentation

#1951 Mention labelled parameters in A tour of OCaml
  data/tutorials/getting-started/1_01_a_tour_of_ocaml.md
Labels: documentation

#1952 Mention labelled parameters in Values and Functions
  data/tutorials/language/0it_00_values_functions.md
Labels: documentation

#1957 Include text on if-then-else and begin-end
  data/tutorials/getting-started/1_01_a_tour_of_ocaml.md
  data/tutorials/getting-started/1_02_your_first_ocaml_program.md
  data/tutorials/language/0it_01_basic_datatypes.md
  data/tutorials/language/0it_02_loops_and_recursion.md
  data/tutorials/language/0it_05_imperative.md
  src/ocamlorg_frontend/pages/learn.eml
  src/ocamlorg_web/lib/redirection.ml
Labels: documentation

#1949 Improve documentation on Editor Support
  data/media/tutorials/emacs-type-info.gif
  data/media/tutorials/vim-type-info.gif
  data/media/tutorials/vscode-ctrl-click.gif
  data/media/tutorials/vscode-hover.gif
  data/media/tutorials/vscode-ocaml-commands.gif
  data/tutorials/getting-started/2_00_editor_setup.md
  data/tutorials/platform/bp_06_configuring_your_editor.md
Labels: documentation

#1965 (feat) add prerequisite_tutorials capability
  data/tutorials/language/0it_00_values_functions.md
  data/tutorials/language/0it_01_basic_datatypes.md
  data/tutorials/language/0it_04_labels.md
  data/tutorials/language/0it_05_imperative.md
  data/tutorials/language/3ds_05_seq.md
  data/tutorials/language/5rt_00_memory_representation.md
  src/ocamlorg_data/data.mli
  src/ocamlorg_frontend/pages/tutorial.eml
  src/ocamlorg_web/lib/handler.ml
  tool/ood-gen/lib/tutorial.ml
Labels: documentation
